version: '2.4'

services:
  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=breakfast
      - MYSQL_USER=breakfast-user
      - MYSQL_PASSWORD=breakfast-password
    ports:
      - "3306:3306"
    networks:
      - breakfast
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 30

networks:
  breakfast:
    name: breakfast
